### PR TITLE
Mockup for website

### PR DESCRIPTION
**Pull request by cmdcolin**
This is a new model that tries to incorporate more content into the "jekyll" system, use more jekyll idioms, remove html5up, remove "cruft", etc.

About us
screenshot-localhost 4000 2015-12-20 16-37-31 png resize

### CODE REVIEW

**Comment by cmdcolin** [comment]
Feel free to add feedback and comments

**Comment by cmdcolin** [comment]
Updated mockup:

Adds dates to blog post list
Adds video to homepage
Adds a navbar

screenshot-127 0 0 1 4000 2015-12-29 17-05-47 png resize

**Comment by dmayfieldjones** [comment]
Sexy

**Comment by cmdcolin** [comment]
Thanks! Feel free to ping me if anything needs updates

**Pull request merged**
