### PR TITLE
Mobilefriendly

### PR DESCRIPTION
**Pull request by htruong**
Changed to the layouts so that it is more mobile friendly, get rid of non-resizeable elements, adopt to AMP project guidelines.

### CODE REVIEW

**Comment by cmdcolin** [comment]
Lookin super good I think.

1) There is a mix of tabs and spaces in some files. I'd standardize on 4 spaces :)
2) What is html ⚡? Is it part of the new framework or is there a new framework?
3) Any better alternative to google analytics?
4) Any way to auto-inline that CSS during site build with jekyll? Maybe https://gist.github.com/benedfit/46da533805566141c42f ?
5) The list of blog posts takes up a lot of space, any way to make it more compact? It looks ok on mobile I think, but on desktop I like it being more compact
6) "Watch our film" goes to a random video
7) Depending on what we want, I thought the photogallery and embedded twitter were kind of cool but went away

**Comment by htruong** [comment]
1, OK, I will get the tabs situation resolved.

2, html :zap: is the HTML AMP https://www.ampproject.org/ - makes it load super fast and doesn't lag on mobile. Enforces a bunch of things, so that the page doesn't jerk while loading, and elements don't push other elements while loading (so that you always click on the right thing, not touch on something and it jerks and then you realize you clicked on the thing you don't want to click).

3, If you like GA that'd be fine, I don't have a preferences. I thought it was the GA that was built in into the theme we built on so I removed it. If that's your tracker, I am fine with putting it back.

4, We actually can, just that the jekyll system on github site won't be able to run it, and that'd be a headache. My idea is to get a bash script to put the files into the correct location when we're about to pubish - thoughts?

5, OK, will make it more compact.

6, Film isn't ready for yet, Dustin will fix it and we will have the film link fixed.

7, Photogallery can be added back, it is called the carousel element, but I don't know where to put it.. I haven't fixed the twitter feed, can you have a look at https://ampbyexample.com/components/amp-twitter/ to see if we can insert the whole timeline there?

**Comment by htruong** [comment]
1, Resolved

4, Resolved and now css is automatically compacted use generate_header.sh when updating the css

5, Resolved

6, Wait for Dustin

**Comment by cmdcolin** [comment]
looks super awesome with the images for the blog posts. woooot

**Comment by cmdcolin** [comment]
abs2

**Comment by htruong** [comment]
3, Is fixed, I put the GA back, sorry Colin

6, This is now temporarily commented out, so this should be pretty good now

**Comment by cmdcolin** [comment]
supa!

**Comment by cmdcolin** [comment]
What is sauce/Gettingstarted? Is it an image? It's 10MB but it's a tiny image if I rename to .png :)

**Comment by cmdcolin** [comment]
$ file sauce/Gettingstarted

Gettingstarted: Adobe Photoshop Image, 594 x 380, RGBA, 4x 8-bit channels

**Comment by htruong** [comment]
OK, Got it renamed also renamed sauce to _sauce so it doesn't get automatically processed.

**Comment by cmdcolin** [comment]
nice :) I cleaned up some other random stuff. looks good!

**Pull request merged**
