### PR TITLE
Use Vega library to produce D3 graphs

### PR DESCRIPTION
**Pull request by cmdcolin**
The current D3 code that we were using was getting pretty annoying and hard to work with

I found a package called Vega (https://vega.github.io/vega-lite/) that is pretty awesome and works more like "ggplot" to produce declarative graphs instead of having to code everything.

The results are quite nice IMO and are almost 100% the same as the existing graphs. Here's an example

abc3-fs8

### CODE REVIEW

**Comment by cmdcolin** [comment]
One significant drawback that I haven't figured out yet is that I'm not sure "parametric" data is possible, e.g. we only have f(x)=y instead of f(t)=(x,y), where f(t)=(x,y) is how the old system worked. There are glitches when using a linechart without this ability

**Comment by cmdcolin** [comment]
To workaround the "parametric graph" issue we can just use a scatterplot instead of line plot potentially

**Comment by htruong** [comment]
I'm checking this out.

**Comment by htruong** [comment]
Looks really great to me and it is seems much more performant.

**Comment by cmdcolin** [comment]
Radical. thanks :)

there are a couple weird things I might try to touch up with it, maybe add scatterplots to avoid the line chart problems

**Pull request merged**
