### PR TITLE
New comparison of balloon data blog post

### PR DESCRIPTION
**Pull request by cmdcolin**
Example screenshot

screenshot-localhost 4000 2016-06-09 13-28-20

### CODE REVIEW

**Comment by cmdcolin** [comment]
I don't know why it looks like they launched in different places, but it's pretty close I suppose! I wasn't there for HAB_0 though

**Comment by htruong** [comment]
Holy cow, nice!

**Comment by cmdcolin** [comment]
Thanks :) Took a little "preprocessing" of the data but it is quite nice to render after that!

**Comment by htruong** [comment]
Work on my computer, I have tested with:

Latest Firefox
Latest Safari
Latest Chrome. 

Merged.

**Comment by cmdcolin** [comment]
woot!

**Pull request merged**
