### PR TITLE
Add esri example

### PR DESCRIPTION
**Pull request by cmdcolin**
The javascripts are toooooo goooooood

screenshot-localhost-4000-2017-04-14-11-20-36

Could potentially be expanded even more to do more stuff but this was a fun example

### CODE REVIEW

**Comment by cmdcolin** [comment]
not sure why red path was more choppy

**Comment by cmdcolin** [comment]
Woot

**Comment by htruong** [comment]
L I V E
I
V
E

j/k

This is really impressive given how litlle and concise your code is :)

**Comment by cmdcolin** [comment]
L O N D O N
O
N
D
O
N

**Pull request merged**
